[mongodb]
mongodb-dev.anildevops90.online

[catalogue]
catalogue-dev.anildevops90.online

[all:vars] # you can access below anywhere
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.anildevops90.online